### ISSUE TITLE
demo matlab code using caffe?

### ISSUE THREAD

**Issue by hengck23** [ashafaei/dense-depth-body-parts#1]
Hi, I am running matlab caffe. I download the your caffe model. Do you have matlab demo code for that?
Thanks a lot!

**Comment by hengck23** [comment]
I am not sure if i am correct.
But this is my results

![clipboard08](https://cloud.githubusercontent.com/assets/5112846/16119860/02a0ab62-3410-11e6-8e98-df9dc25105d7.jpg)

matlab code for caffe mode:
addpath('< put your caffe matlab path here!>\matcaffe')

depth_image = importdata('sample.png'); 
margin_1 = sum(depth_image.alpha, 1);
margin_2 = sum(depth_image.alpha, 2);
top = find(margin_2, 1, 'first');
bottom = find(margin_2, 1, 'last');
left = find(margin_1, 1, 'first');
right = find(margin_1, 1, 'last');

assert(top<bottom && left<right, 'Top/Bottom & Left/Right are not consistent');
width = right-left+1;
height = bottom-top+1;

% Crop the image
depth_image.cdata = depth_image.cdata(top:bottom, left:right, 1);
depth_image.alpha = depth_image.alpha(top:bottom, left:right);

target_window = 190;
margin = 30;
if height > width,
    scaler = [target_window NaN];
else
    scaler = [NaN target_window];    
end

% Scale the image
depth_im = imresize(depth_image.cdata, scaler, 'lanczos2');
depth_mask = imresize(depth_image.alpha, scaler, 'nearest') == 255;

average_depth = mean(depth_im(depth_mask));
depth_im(depth_mask) = uint8(int64(depth_im(depth_mask)) + int64(55-average_depth));
depth_im(~depth_mask) = 255;

depth_im = single(depth_im)/255;
[height, width] = size(depth_im);

final_depth_image = ones(target_window + 2*margin, target_window + 2*margin, 'single');
final_depth_mask = zeros([target_window + 2*margin, target_window + 2*margin], 'uint8');
loc_x = floor((target_window + 2*margin - width)/2)+1;
loc_y = floor((target_window + 2*margin - height)/2)+1;

final_depth_image(loc_y:loc_y+height-1, loc_x:loc_x+width-1) = depth_im;
final_depth_mask(loc_y:loc_y+height-1, loc_x:loc_x+width-1) = depth_mask*255;

%% Load and prepare the network.
deployFile='C:\Users\root\Desktop\3d_pose\caffe\deploy.prototxt';
caffemodel='C:\Users\root\Desktop\3d_pose\caffe\hardpose_69k.caffemodel';

net = caffe.Net(deployFile, caffemodel, 'test');
net.forward({final_depth_image});
blob_id_C = strfind(net.blob_names, 'prob');
blob_id = find(not(cellfun('isempty', blob_id_C)));
blob_id = blob_id(end);
prediction = net.blob_vec(blob_id).get_data();	
 

[~, classes] = max(prediction, [], 3);
classes(~final_depth_mask) = 0;
imagesc(classes);

**Comment by ashafaei** [comment]
@hengck23 
Hello hengck23,

Caffe and Matlab differ in the dimension order of the input. In Matlab everything is HxW while in Caffe it is WxH, so you need to transpose the input and send it to Caffe, and also you need to transpose the output prediction before using it. I can not test this right now, but I believe if you say

~~~~matlab
net.forward({final_depth_image'});
...
[~, classes] = max(prediction', [], 3);
~~~~

It should work.

If your input batch size is greater than one, the transpose operator ' will not work and you'll need to use the ``permute`` function.

~~~~matlab
final_depth_image = permute(final_depth_image, [2 1 3 4]);
...
prediction = permute(prediction, [2 1 3 4]);
~~~~

**Comment by hengck23** [comment]
here are the changes i made for transposing:
net.forward({final_depth_image'});
...
[~, classes] = max(prediction, [], 3);
classes = classes'

if it is wrong, please let me know. Do you have the results image for matConvNet?

![clipboard02](https://cloud.githubusercontent.com/assets/5112846/16140261/922c3c1c-3481-11e6-865c-c722ae410af3.jpg)

**Comment by hengck23** [comment]
Here is the same results as above with out masking. i.e. commenting of
%classes(~final_depth_mask) = 0;
![clipboard02a](https://cloud.githubusercontent.com/assets/5112846/16140510/cd2cdeaa-3483-11e6-92a2-639f010e99f8.jpg)

**Comment by ashafaei** [comment]
@hengck23 
Thank you for the update, I'm glad it worked out. I also think you'd find the following useful.

The network has extra output on channels 17, and 18 (base 1) that are not used. Ignoring 17, and 18, once you reindex, the remainder is as follows. ``prediction(:, :, [1:16 19:45])``
![alt text](https://github.com/ashafaei/dense-depth-body-parts/raw/master/calss_ref.png "Class Reference")

All the best.
