### ISSUE TITLE
deploy prototxt - crop parameters

### ISSUE THREAD

**Issue by ananth-jauntxr** [ashafaei/dense-depth-body-parts#11]
Hi, thanks for the code.

Is it possible to obtain a deploy or train prototxt file for this model? I am not sure about the cropping parameters (axis and offset) being used in the layers. Could you help me with that?

thanks,
Ananth

**Comment by ashafaei** [comment]
Hello Ananth,

See the project page here https://www.cs.ubc.ca/~shafaei/homepage/projects/crv16.php, The Caffe archive should have the deploy prototxt.

Cheers,
Alireza

**Comment by ananth-jauntxr** [comment]
Great, thanks!
