### ISSUE TITLE
Using the python version

### ISSUE THREAD

**Issue by mpouprod** [ashafaei/dense-depth-body-parts#13]
Hello,

I was searching for papers about pose estimation and human body segmentation and i ran into your paper. So, i was trying to run the python version, but i am facing some problems. More specifically, i tried to run the matdoc.py file for the demo_render.m file. Once the file is parsed i get the error message "Could not find a MATLAB function", which means that no fuction was found. Is it possible that you provide some advice about this? I also noticed that the requirements.txt file mentioned in the README.md file is missing. Is it possible that i am missing some library or something? I would really appreciate your input on this. Thank you for your time!

**Comment by ashafaei** [comment]
Here's what I recommend you do:

1. Install Anaconda with Python 2.7 [https://www.anaconda.com/distribution/](https://www.anaconda.com/distribution/)
2. After setting it up, open a terminal (or command prompt) inside Anaconda and install pip:
  `conda install pip`
3. Then install opencv-python:
  `pip install opencv-python`
4. Then run the python script
 `python classification_demo.py`

I'm not exactly sure what has happened, but the classification_demo.py is self-contained and has no extra `Matlab Function` dependencies.

**Comment by mpouprod** [comment]
I think i didn't make my self very clear. Sorry about that. I can run the
classification_demo.py. My problem is with this version
https://github.com/surajpaib/dense-depth-body-parts where i can not post an
issue because that project was fork by this one. Anyway i would like to
know:
1) There was supposed to be a requirements.txt file according to the readme
file. Is it possible to know which are those requirements?
2) I am trying to run the matdoc.py file from here
https://github.com/vlfeat/matconvnet/tree/master/doc using the demo_render
file from here https://github.com/ashafaei/ubc3v/tree/master/demos . As i
understood the matdoc.py file is like a wrapper to run .m files from
python. You also mentioned this
https://github.com/surajpaib/dense-depth-body-parts in the readme file of
your repo. Could it be possible that you display an example on how to use
the matdoc.py to run a .m file ?
Again thank you very much for your time! Really appreciate it!


Στις Τετ, 12 Φεβ 2020, 11:06 μ.μ. ο χρήστης Alireza Shafaei <
notifications@github.com> έγραψε:

**Comment by ashafaei** [comment]
- As far as I know, the only requirement on top of an Anaconda installation is `opencv-python` for 'https://github.com/surajpaib/dense-depth-body-parts'. You don't need any of the external dependencies in this repository. The python script already loads the model and performs classification. The dependencies are for the Matlab version, which I *do not think anybody should use anymore*.
- I do not remember anything about a `matdoc.py`. The UBC3V dataset is written in Matlab, but it is easy to use in Python -- Though you will have to implement everything from scratch. The image files are the same. You only will need a library to open Matlab data binaries from the dataset which I believe numpy supports out of the box. And you need to read the binary files only if you wish to reconstruct the 3d point cloud. The images are good for training and testing without any change.

For the python version, you only need
- The caffe model files https://github.com/surajpaib/dense-depth-body-parts/tree/master/caffe_models
- The script https://github.com/surajpaib/dense-depth-body-parts/blob/master/classification_demo.py
- The sample image https://github.com/surajpaib/dense-depth-body-parts/blob/master/sample.png
- Numpy and opencv-python.

**Comment by surajpaib** [comment]
Hi! I added the requirements file now! I don't know how I missed it earlier. Just caught on to this thread when I saw my repo being starred. Thanks for the kudos @ashafaei . I'll see if I can take a look at it over the weekend and make a quick refactor to make the code easier to use
