### ISSUE TITLE
rotation scripts

### ISSUE THREAD

**Issue by rlabuguen** [ashafaei/dense-depth-body-parts#4]
Dear Mr. Shafaei,

I am trying the demo_render.m in UBC3V toolkit. For which, I got the following errors:

Error in generate_cloud_camera (line 57)
rot_mat =   rotz(0*camera.rotation(3)) ...

Error in generate_cloud_instance (line 11)
    [ cloud, labels, full_cloud, full_colors, mask ] = generate_cloud_camera( instance.(cameras{c}), mapper );

Error in render_multicam (line 24)
clouds = generate_cloud_instance(instance, mapper);

Error in demo_render (line 34)
render_multicam(instances(8), mapper);

I believe the error relates to the rotation scripts/functions to be used.
If it is possible, could you please show the functions rotx, roty and rotz. 
How are these formulated? Is it similar to the rotation matrices in vector algebra?

Thank you very much,

Rollyn Labuguen

**Comment by ashafaei** [comment]
Hello @rlabuguen ,
These three functions: `rotx, roty, rotz` are part of the Matlab toolkit. See this link [https://www.mathworks.com/help/phased/ref/rotx.html](https://www.mathworks.com/help/phased/ref/rotx.html). Yes, they are the rotation matrices from linear algebra.
![](http://i.imgur.com/Z6geYpC.png)

As you can see it is easy to implement them yourself and you don't need Matlab's implementation.

**Comment by rlabuguen** [comment]
Thanks! I was able to render it.
