### ISSUE TITLE
Number of output of deconvolution or convolution layer

### ISSUE THREAD

**Issue by gizmo1904** [ashafaei/dense-depth-body-parts#5]
Dear Mr. Shafaei,
I was looking into your model and I am confused by the number of outputs in different layers. In the deploy.prototxt the output size is 46, in the model overview it's 44 (43 classes + background). Could you please explain that to me? 
I've got your model from here: http://www.cs.ubc.ca/~shafaei/homepage/projects/datasets/caffe_crv16.zip

Thank you very much!

**Comment by ashafaei** [comment]
Hello @gizmo1904,

Thank you for your question.

The _texture_ that I used to generate the data has 45 regions (see the dataset [UBC3v](https://github.com/ashafaei/ubc3v) and the 3d models and textures [3dmodels.tar.gz](http://www.cs.ubc.ca/~shafaei/dataset/3dmodels.tar.gz)). However, two of the regions in the _texture file_ never shows up in the rendered images. When I started the training, I was not aware that the two classes in the texture are actually never rendered, which lead to two useless classes in the output of the network. I later simply ignored the two classes as they never became activated anyway. You can easily identify the _extra useless classes_ by examining the activations.

**Comment by gizmo1904** [comment]
Thank you for clearing that up. Have a nice day.
